// THIS FILE IS AUTOGENERATED FROM scripts/include.go EDITS WILL BE SQUISHED
// IT IS MEANT FOR HOLDING CONFIGURABLE OPTIONS
package denvlib

const (
settings_yml = `denvhome: ~/.denv
infofile: .denvinfo
ignorefile: .denvignore
restoredenv: .restore
prescript: .denvpre
postscript: .denvpost
`
_default_denvignore = `.bash_history
.gnupg
.npm
.nvm
.rvm
.gimme
.cache
.gem
.bundle
.erlang.cookie
.git
.denv*
.ssh
.viminfo
`
Version = "123014f"
)
